version: '3.8'
services:
  pg1:
    image: postgres:14.5
    container_name: pg1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test
    # https://github.com/docker-library/postgres/issues/177#issuecomment-655527349
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    ports:
      - "5434:5432"
  redis:
    image: "redis:7.2.3-alpine"
    container_name: redis1
    ports:
      - "6380:6379"
    # use redis config from host machine
    volumes:
      - ./caching/configs/redis.conf:/usr/local/etc/redis/redis.conf