version: '3.8'
services:
  pg1:
    image: postgres:14.5
    container_name: pg1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test
    ports:
      - "5434:5432"
  redis:
    image: "redis:7.2.3-alpine"
    container_name: redis1
    ports:
      - "6380:6379"